### ISSUE TITLE
Set configuration for Azure Function

### ISSUE THREAD

**Issue by UncountedBrute3** [Avanade/UnitTestEx#77]
When setting up the 

```csharp
FunctionTester<FunctionProgram> test = CreateFunctionTester<FunctionProgram>();
```

I can see how to add services. I do not see a way to set the configuration to overide local.settings.json. The use case for this, is I have feature toggles based on configuration and need to configure this to get the test to pass.

How can I do this?

**Comment by chullybun** [comment]
Hi @UncountedBrute3, great question and fortunately I have a positive answer for you; but to be fair, it was probably not that obvious.

There are two options:
1. You can add a [`appsettings.unittest.json`](https://github.com/Avanade/unittestex#appsettingsunittestjson) to the test project; this will alter the configuration for all tests.
2. You can specify overrides per test via the `Create` method by passing in via the `additionalConfiguration` parameter; this takes a key/value pairs for the configuration. 

See this [unit test](https://github.com/Avanade/UnitTestEx/blob/c302260bf56ced824bedeac3d275618c5510f068/tests/UnitTestEx.NUnit.Test/ServiceBusFunctionTest.cs#L150) for an example: `FunctionTester.Create<Startup>(additionalConfiguration: new Dictionary<string, string>(new KeyValuePair<string, string>[] { new("SpecialKey", "NotSoSpecial") }));`

Cheers,
Eric...

**Comment by karpikpl** [comment]
Hey @chullybun, would it be possible to add same option for `ApiTester` ?

**Comment by chullybun** [comment]
@karpikpl - done! See updated packages: https://www.nuget.org/packages/UnitTestEx/5.2.0

**Comment by karpikpl** [comment]
thanks! that's a quick turnaround :)
Great customer service :P
